### ISSUE TITLE
Fix make_model Documentation

### ISSUE THREAD

**Issue by cannin** [cannin/enhance_nlp_interaction_network_gsoc2020#11]
It looks like there is a bug in the help (highlighted lines in the figure), if so can you correct and pull request? 

<img width="699" alt="Screen Shot 2020-07-14 at 9 05 23 PM" src="https://user-images.githubusercontent.com/790284/87491290-c29e7980-c615-11ea-9e24-2a9326a4ee95.png">

**Comment by PritiShaw** [comment]
I tried to fix the error, it was related to indentation
But when I was trying to build in ReadTheDocs, I am getting `Command killed due to excessive memory consumption`
I am not sure how should I test it,  
It Built successfully once following was the output
![image](https://user-images.githubusercontent.com/34039705/87584806-ac6ae900-c6fb-11ea-8b75-42725ba25257.png)

**Comment by PritiShaw** [comment]
> I tried to fix the error, it was related to indentation
> But when I was trying to build in ReadTheDocs, I am getting `Command killed due to excessive memory consumption`
> I am not sure how should I test it,

Build successfully, It was configuration mistake from my side
[Output ](https://indrap.readthedocs.io/en/latest/modules/assemblers/html_assembler.html#indra.assemblers.html.assembler.HtmlAssembler.make_model)

**Comment by cannin** [comment]
Thanks. Please submit a pull request.

**Comment by PritiShaw** [comment]
PR Merged [https://github.com/sorgerlab/indra/pull/1135](https://github.com/sorgerlab/indra/pull/1135)
